# Generated by Django 4.2.5 on 2023-09-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=10)),
                ('date_created', models.DateField()),
                ('date_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('date_due', models.DateField()),
                ('task_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tag')),
            ],
        ),
    ]
